App\Entity\CheeseListing:
  attributes:
    name:
      groups:
        - 'cheeselisting-read'
        - 'cheeselisting-write'
        - 'user-read'
        - 'cheeselisting-item-read'
        - 'cheeselisting-item-write'
    description:
      groups:
        - 'cheeselisting-read'
        - 'cheeselisting-item-read'
      price:
        groups:
          - 'cheeselisting-read'
          - 'cheeselisting-write'
          - 'user-read'
          - 'cheeselisting-item-read'
      owner:
        groups:
          - 'cheeselisting-read'
          - 'cheeselisting-write'
          - 'cheeselisting-item-read'
          - 'cheeselisting-item-write'
      owner_id:
        groups:
          - 'cheeselisting-read'
          - 'cheeselisting-item-read'
      username:
        groups:
          - 'user-read'

