App\Entity\User:
  collectionOperations:
    get:
    post:
      normalization_context:
        groups:
          - 'user-read'
  itemOperations:
    get:
    put:
    delete:
      normalization_context:
        groups:
          - 'user-item-read'